baseurl: ""
safe: false
url: "https://somdev.in"
title: "Somdev Sangwan"
permalink: pretty

collections:
  blog:
    output: true
    permalink: /blog/:name
  essays:
    output: true
    permalink: /essays/:name/

defaults:
  - scope:
      path: ""
      type: blog
    values:
      layout: post
      author: Somdev Sangwan
      type: tech
  - scope:
      path: ""
      type: essays
    values:
      layout: post
      author: Somdev Sangwan
      type: philosophy

description: "Somdev Sangwan (s0md3v)"
author:
  name: Somdev Sangwan
  twitter: s0md3v
# Social handles
social:
  twitter: s0md3v
  github: s0md3v
  linkedin: s0md3v
  instagram: s0md3v

# Required for jekyll-seo-tag
twitter:
  username: s0md3v

plugins:
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-redirect-from

redirect_from:
  json: false

jekyll-minifier:
  uglifier_args:
    harmony: true
  exclude:
    - "playground/**/*"

sass:
  style: compressed

# Default social image
image:
  path: /assets/images/profile.jpg

exclude:
  - "denoise*.html"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - mockups
  - keys.txt
  - .git
